### PR TITLE
Async support

### LINKED ISSUE #10: Implement asynchronous execution of commands
Currently asynchronous execution is not straight away supported by erlimem

### PR DESCRIPTION
**Pull request by shamis**
Fixes #10

### CODE REVIEW

**Comment by c-bik** [comment]
@acautin and @shamis
I don't understand why library code like `erlimem` or `imem_server` must be aware of app level API like `request_metric` etc.

**Comment by acautin** [comment]
@c-bik for metrics we need to send the reply only when it is a metric result. btw imem_server is not involved in this...

**Comment by c-bik** [comment]
@acautin 
Try and alternate approach. From the calling point:
```erlang
...
ErlimemSession = erlimem:open(...),
% synchronous call return value of imem_server apply call
ok = ErlimemSession:run_cmd(..., request_metric, [self(), ...]),
% can be a gen_server:handle_info too
receive
  {metric, Metric} -> ...
end
...
```
This eliminates the need for a separate async API in erlimem

**Comment by acautin** [comment]
@c-bik we didn't find the way to implement it like that, maybe you could help us by creating the pr ?

**Comment by acautin** [comment]
@c-bik also the caller should not be stopped because the connection to the other side is slow (this should be an async call after all), we would need to give a very short timeout that overrides the long one included by default.

**Comment by shamis** [comment]
Closing this as an alternate approach was agreed on

**Pull request closed without merging**
